# eval `ssh-agent -s` && ssh-add ~/nodekey
# docker compose --profile node up -d --build --force-recreate
# eval `ssh-agent -s` && ssh-add ~/nodekey && git pull && docker compose --profile node up -d --build --force-recreate

name: notifyu-node
services:
  # ###################################################################
  # Snapshot
  # ###################################################################
  snapshot:
    build:
      context: ./snapshot
      dockerfile: Dockerfile
    profiles: [snapshot]
    user: root
    volumes:
      - ./shared-volume:/data
  # snapshot:
  #   image: alpine:latest
  #   profiles: [snapshot]
  #   volumes:
  #     - ./snapshot:/root/config:ro
  #     - ./shared-volume:/data
  #   entrypoint: /root/config/entrypoint.sh
  # ###################################################################
  # Node Components
  # ###################################################################
  proxy:
    image: nginx:1.28
    profiles: [node]
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./proxy:/etc/nginx:ro
    command: [nginx-debug, "-g", "daemon off;"]
  load-balancer:
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    profiles: [node]
    restart: unless-stopped
    user: root
    ports:
      - 11111:11111 # RPC Balancer
      - 11112:11112 # API Balancer
    volumes:
      - ./load-balancer:/usr/local/config:ro
  thornode1:
    container_name: notifyu-node-thornode-1
    build:
      context: ./thornode
      dockerfile: Dockerfile
    profiles: [node]
    restart: unless-stopped
    volumes:
      - thornode-volume-1:/root/.thornode
      - ./thornode:/root/config:ro
      - ./shared-volume:/root/shared-volume:ro
  thornode2:
    container_name: notifyu-node-thornode-2
    build:
      context: ./thornode
      dockerfile: Dockerfile
    profiles: [node]
    restart: unless-stopped
    volumes:
      - thornode-volume-2:/root/.thornode
      - ./thornode:/root/config:ro
      - ./shared-volume:/root/shared-volume:ro
  thornode3:
    container_name: notifyu-node-thornode-3
    build:
      context: ./thornode
      dockerfile: Dockerfile
    profiles: [node]
    restart: unless-stopped
    volumes:
      - thornode-volume-3:/root/.thornode
      - ./thornode:/root/config:ro
      - ./shared-volume:/root/shared-volume:ro

  directory-monitor:
    build: ./directory-monitor
    profiles: [node]
    restart: unless-stopped
    volumes:
      - /usr/bin/docker:/usr/bin/docker # (LINUX ONLY) Docker commands
      - /var/run/docker.sock:/var/run/docker.sock # (LINUX ONLY) Give access of host Docker instances to container
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins # (LINUX ONLY) Docker compose commands

volumes:
  thornode-volume-1:
  thornode-volume-2:
  thornode-volume-3:
